### ISSUE TITLE
src/cave.js doesn't work properly

### ISSUE THREAD

**Issue by StephanGerbeth** [bevacqua/cave#1]
Hi,

I tried your script but it doesn't work properly. 
Doesn't work: 

```
var cave = require('cave');
var fs = require('fs');
cave('deploy/css/style.css', fs.readFileSync('deploy/css/critical.css', { encoding: 'utf8' }), function() {
     console.log('OUTPUT');
 })
```

Error: `Warning: Maximum call stack size exceeded Use --force to continue.`

It seems to the css library has some problems to parse the css-file.

Works:
`cat deploy/css/style.css | ./node_modules/cave/bin/cave deploy/css/critical.css > deploy/css/slim.css`

How can i fix it? Can you help me?

Kind regards
Stephan

**Comment by bevacqua** [comment]
you should use the API as described in the readme.

``` js
var cave = require('cave');
var fs = require('fs');
var css = fs.readFileSync('deploy/css/critical.css', { encoding: 'utf8' });
cave('deploy/css/style.css', { css: css }, function() {
   console.log('OUTPUT');
 });
```

**Comment by StephanGerbeth** [comment]
ah i forgot to add the critical css as object.
i implemented your lines of code but it doesn't work.
I also got the error message: Warning: Maximum call stack size exceeded Use --force to continue.

When i debug your code i recognized the error will happen in src/cave.js line 8. It breaks when the process tries to parse the css of style.css. the read command works fine but i think css.parse cant interpret the text input.
I stripped the style.css to only one css selector, but i resolved the same error.
Do you have any idea how to solve it?

Kind regards
Stephan

**Comment by bevacqua** [comment]
See the test case. https://github.com/bevacqua/cave/blob/master/test/cave.js
That works
