### ISSUE TITLE
Done callback

### ISSUE THREAD

**Issue by davidchase** [bevacqua/cave#2]
Was the done callback removed? just curious

``` js
var diff = cave(pathToFile('style.css'), {
            css: criticalCss
});
console.log(diff) // outputs the css
```

but adding a function after the css object never gets called

``` js
var diff = cave(pathToFile('style.css'), {
            css: criticalCss
}, function(){
   console.log('done'); // never gets called
});
```

**Comment by bevacqua** [comment]
Because every tool `cave` uses is synchronous already, so it was kind of pointless. You made me realize I need to update the `README`, though!

**Comment by davidchase** [comment]
yeah that threw me off, but i figure as much thanks

**Comment by bevacqua** [comment]
Oh also, CLI tools are typically okay being synchronous, since performance isn't such a huge factor there either (and you typically have just the one code path too).
